/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java21;

import de.codepitbull.module.example.Dependency;
import de.codepitbull.module.example.MyService;

import java.util.ServiceLoader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ServiceLoader.load(MyService.class).stream().forEach(my -> System.out.println("Found a service: " + my.get().test()));
        System.out.println(Dependency.hello());
    }
}
